# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPdftest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pdftest(self):
    self.driver.get("https://www.repository.cam.ac.uk/home")
    self.driver.set_window_size(550, 693)
    self.driver.execute_script("window.scrollTo(0,185.60000610351562)")
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .lead").click()
    self.driver.execute_script("window.scrollTo(0,102.4000015258789)")
    self.driver.execute_script("window.scrollTo(0,129.60000610351562)")
  
